require("config.treesitter")
require("config.cmp")
require("config.formatter")
require("config.telescope")
require("config.nvim-tree")
require("config.ultisnips")
require("config.rust-tools")
require("config.which-key")
